# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: innfactory/gcloud-scala-ci:latest
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: test
          POSTGRES_PASSWORD: password
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
        
      # run tests!
      - run: cat /dev/null | sbt test:test
